//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 10:03:45 PM CET 
//


package com.upsam.hospital.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="label2" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="c7"/>
 *             &lt;enumeration value="l asis"/>
 *             &lt;enumeration value="l bar 1"/>
 *             &lt;enumeration value="l bar 2"/>
 *             &lt;enumeration value="l knee 1"/>
 *             &lt;enumeration value="l knee 2"/>
 *             &lt;enumeration value="l mall"/>
 *             &lt;enumeration value="l should"/>
 *             &lt;enumeration value="l thigh"/>
 *             &lt;enumeration value="r asis"/>
 *             &lt;enumeration value="r bar 1"/>
 *             &lt;enumeration value="r bar 2"/>
 *             &lt;enumeration value="r knee 1"/>
 *             &lt;enumeration value="r knee 2"/>
 *             &lt;enumeration value="r mall"/>
 *             &lt;enumeration value="r should"/>
 *             &lt;enumeration value="r thigh"/>
 *             &lt;enumeration value="sacrum"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="label1" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="c7"/>
 *             &lt;enumeration value="l asis"/>
 *             &lt;enumeration value="l bar 1"/>
 *             &lt;enumeration value="l bar 2"/>
 *             &lt;enumeration value="l knee 1"/>
 *             &lt;enumeration value="l knee 2"/>
 *             &lt;enumeration value="l mall"/>
 *             &lt;enumeration value="l met"/>
 *             &lt;enumeration value="l should"/>
 *             &lt;enumeration value="l thigh"/>
 *             &lt;enumeration value="r asis"/>
 *             &lt;enumeration value="r bar 1"/>
 *             &lt;enumeration value="r bar 2"/>
 *             &lt;enumeration value="r knee 1"/>
 *             &lt;enumeration value="r knee 2"/>
 *             &lt;enumeration value="r mall"/>
 *             &lt;enumeration value="r met"/>
 *             &lt;enumeration value="r should"/>
 *             &lt;enumeration value="r thigh"/>
 *             &lt;enumeration value="sacrum"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "link")
public class Link {

    @XmlAttribute(name = "label2", required = true)
    protected String label2;
    @XmlAttribute(name = "label1", required = true)
    protected String label1;

    /**
     * Gets the value of the label2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel2() {
        return label2;
    }

    /**
     * Sets the value of the label2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel2(String value) {
        this.label2 = value;
    }

    /**
     * Gets the value of the label1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * Sets the value of the label1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel1(String value) {
        this.label1 = value;
    }

}
