//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 10:03:45 PM CET 
//


package com.upsam.hospital.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}reference"/>
 *         &lt;element ref="{}event" maxOccurs="unbounded"/>
 *         &lt;element ref="{}track1d" maxOccurs="unbounded"/>
 *         &lt;element ref="{}track1d_band" maxOccurs="unbounded"/>
 *         &lt;element ref="{}time" maxOccurs="unbounded"/>
 *         &lt;element ref="{}time_band" maxOccurs="unbounded"/>
 *         &lt;element ref="{}scalar" maxOccurs="unbounded"/>
 *         &lt;element ref="{}freq" maxOccurs="unbounded"/>
 *         &lt;element ref="{}vel1d" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="label" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="description" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reference",
    "event",
    "track1D",
    "track1DBand",
    "time",
    "timeBand",
    "scalar",
    "freq",
    "vel1D"
})
@XmlRootElement(name = "static")
public class Static {

    @XmlElement(required = true)
    protected Reference reference;
    @XmlElement(required = true)
    protected List<Event> event;
    @XmlElement(name = "track1d", required = true)
    protected List<Track1D> track1D;
    @XmlElement(name = "track1d_band", required = true)
    protected List<Track1DBand> track1DBand;
    @XmlElement(required = true)
    protected List<Time> time;
    @XmlElement(name = "time_band", required = true)
    protected List<TimeBand> timeBand;
    @XmlElement(required = true)
    protected List<Scalar> scalar;
    @XmlElement(required = true)
    protected List<Freq> freq;
    @XmlElement(name = "vel1d", required = true)
    protected List<Vel1D> vel1D;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "description", required = true)
    protected String description;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Event }
     * 
     * 
     */
    public List<Event> getEvent() {
        if (event == null) {
            event = new ArrayList<Event>();
        }
        return this.event;
    }

    /**
     * Gets the value of the track1D property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the track1D property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrack1D().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Track1D }
     * 
     * 
     */
    public List<Track1D> getTrack1D() {
        if (track1D == null) {
            track1D = new ArrayList<Track1D>();
        }
        return this.track1D;
    }

    /**
     * Gets the value of the track1DBand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the track1DBand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrack1DBand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Track1DBand }
     * 
     * 
     */
    public List<Track1DBand> getTrack1DBand() {
        if (track1DBand == null) {
            track1DBand = new ArrayList<Track1DBand>();
        }
        return this.track1DBand;
    }

    /**
     * Gets the value of the time property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the time property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Time }
     * 
     * 
     */
    public List<Time> getTime() {
        if (time == null) {
            time = new ArrayList<Time>();
        }
        return this.time;
    }

    /**
     * Gets the value of the timeBand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeBand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeBand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeBand }
     * 
     * 
     */
    public List<TimeBand> getTimeBand() {
        if (timeBand == null) {
            timeBand = new ArrayList<TimeBand>();
        }
        return this.timeBand;
    }

    /**
     * Gets the value of the scalar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scalar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScalar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Scalar }
     * 
     * 
     */
    public List<Scalar> getScalar() {
        if (scalar == null) {
            scalar = new ArrayList<Scalar>();
        }
        return this.scalar;
    }

    /**
     * Gets the value of the freq property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freq property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreq().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Freq }
     * 
     * 
     */
    public List<Freq> getFreq() {
        if (freq == null) {
            freq = new ArrayList<Freq>();
        }
        return this.freq;
    }

    /**
     * Gets the value of the vel1D property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vel1D property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVel1D().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Vel1D }
     * 
     * 
     */
    public List<Vel1D> getVel1D() {
        if (vel1D == null) {
            vel1D = new ArrayList<Vel1D>();
        }
        return this.vel1D;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
