//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.24 at 10:03:45 PM CET 
//


package com.upsam.hospital.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="scaleFactor" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;enumeration value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nSegs" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="17"/>
 *             &lt;enumeration value="18"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="29"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="34"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="43"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="9"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nPoints" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1168"/>
 *             &lt;enumeration value="1169"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="120"/>
 *             &lt;enumeration value="1205"/>
 *             &lt;enumeration value="123"/>
 *             &lt;enumeration value="128"/>
 *             &lt;enumeration value="1316"/>
 *             &lt;enumeration value="136"/>
 *             &lt;enumeration value="158"/>
 *             &lt;enumeration value="1597"/>
 *             &lt;enumeration value="1602"/>
 *             &lt;enumeration value="17"/>
 *             &lt;enumeration value="1720"/>
 *             &lt;enumeration value="1923"/>
 *             &lt;enumeration value="1949"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="2010"/>
 *             &lt;enumeration value="2019"/>
 *             &lt;enumeration value="2025"/>
 *             &lt;enumeration value="2032"/>
 *             &lt;enumeration value="2053"/>
 *             &lt;enumeration value="2141"/>
 *             &lt;enumeration value="218"/>
 *             &lt;enumeration value="2270"/>
 *             &lt;enumeration value="2274"/>
 *             &lt;enumeration value="233"/>
 *             &lt;enumeration value="2402"/>
 *             &lt;enumeration value="2448"/>
 *             &lt;enumeration value="2456"/>
 *             &lt;enumeration value="248"/>
 *             &lt;enumeration value="2493"/>
 *             &lt;enumeration value="25"/>
 *             &lt;enumeration value="2615"/>
 *             &lt;enumeration value="2631"/>
 *             &lt;enumeration value="2634"/>
 *             &lt;enumeration value="2695"/>
 *             &lt;enumeration value="2710"/>
 *             &lt;enumeration value="275"/>
 *             &lt;enumeration value="28"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="33"/>
 *             &lt;enumeration value="38"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="41"/>
 *             &lt;enumeration value="42"/>
 *             &lt;enumeration value="46"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="53"/>
 *             &lt;enumeration value="55"/>
 *             &lt;enumeration value="56"/>
 *             &lt;enumeration value="57"/>
 *             &lt;enumeration value="588"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="65"/>
 *             &lt;enumeration value="68"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="721"/>
 *             &lt;enumeration value="735"/>
 *             &lt;enumeration value="79"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="80"/>
 *             &lt;enumeration value="99"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nItems" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;enumeration value="-1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="label" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="LA"/>
 *             &lt;enumeration value="LHP"/>
 *             &lt;enumeration value="LK"/>
 *             &lt;enumeration value="LT"/>
 *             &lt;enumeration value="RA"/>
 *             &lt;enumeration value="RHP"/>
 *             &lt;enumeration value="RK"/>
 *             &lt;enumeration value="RT"/>
 *             &lt;enumeration value="[0]"/>
 *             &lt;enumeration value="[100]"/>
 *             &lt;enumeration value="[101]"/>
 *             &lt;enumeration value="[102]"/>
 *             &lt;enumeration value="[103]"/>
 *             &lt;enumeration value="[107]"/>
 *             &lt;enumeration value="[108]"/>
 *             &lt;enumeration value="[109]"/>
 *             &lt;enumeration value="[10]"/>
 *             &lt;enumeration value="[110]"/>
 *             &lt;enumeration value="[115]"/>
 *             &lt;enumeration value="[116]"/>
 *             &lt;enumeration value="[118]"/>
 *             &lt;enumeration value="[11]"/>
 *             &lt;enumeration value="[120]"/>
 *             &lt;enumeration value="[121]"/>
 *             &lt;enumeration value="[122]"/>
 *             &lt;enumeration value="[123]"/>
 *             &lt;enumeration value="[124]"/>
 *             &lt;enumeration value="[125]"/>
 *             &lt;enumeration value="[126]"/>
 *             &lt;enumeration value="[127]"/>
 *             &lt;enumeration value="[128]"/>
 *             &lt;enumeration value="[129]"/>
 *             &lt;enumeration value="[12]"/>
 *             &lt;enumeration value="[130]"/>
 *             &lt;enumeration value="[131]"/>
 *             &lt;enumeration value="[132]"/>
 *             &lt;enumeration value="[133]"/>
 *             &lt;enumeration value="[134]"/>
 *             &lt;enumeration value="[135]"/>
 *             &lt;enumeration value="[136]"/>
 *             &lt;enumeration value="[137]"/>
 *             &lt;enumeration value="[138]"/>
 *             &lt;enumeration value="[139]"/>
 *             &lt;enumeration value="[13]"/>
 *             &lt;enumeration value="[140]"/>
 *             &lt;enumeration value="[141]"/>
 *             &lt;enumeration value="[142]"/>
 *             &lt;enumeration value="[143]"/>
 *             &lt;enumeration value="[144]"/>
 *             &lt;enumeration value="[145]"/>
 *             &lt;enumeration value="[146]"/>
 *             &lt;enumeration value="[147]"/>
 *             &lt;enumeration value="[148]"/>
 *             &lt;enumeration value="[149]"/>
 *             &lt;enumeration value="[14]"/>
 *             &lt;enumeration value="[150]"/>
 *             &lt;enumeration value="[151]"/>
 *             &lt;enumeration value="[152]"/>
 *             &lt;enumeration value="[153]"/>
 *             &lt;enumeration value="[154]"/>
 *             &lt;enumeration value="[155]"/>
 *             &lt;enumeration value="[156]"/>
 *             &lt;enumeration value="[157]"/>
 *             &lt;enumeration value="[158]"/>
 *             &lt;enumeration value="[159]"/>
 *             &lt;enumeration value="[15]"/>
 *             &lt;enumeration value="[160]"/>
 *             &lt;enumeration value="[161]"/>
 *             &lt;enumeration value="[162]"/>
 *             &lt;enumeration value="[163]"/>
 *             &lt;enumeration value="[164]"/>
 *             &lt;enumeration value="[165]"/>
 *             &lt;enumeration value="[16]"/>
 *             &lt;enumeration value="[17]"/>
 *             &lt;enumeration value="[18]"/>
 *             &lt;enumeration value="[19]"/>
 *             &lt;enumeration value="[1]"/>
 *             &lt;enumeration value="[20]"/>
 *             &lt;enumeration value="[21]"/>
 *             &lt;enumeration value="[22]"/>
 *             &lt;enumeration value="[23]"/>
 *             &lt;enumeration value="[24]"/>
 *             &lt;enumeration value="[26]"/>
 *             &lt;enumeration value="[28]"/>
 *             &lt;enumeration value="[2]"/>
 *             &lt;enumeration value="[30]"/>
 *             &lt;enumeration value="[31]"/>
 *             &lt;enumeration value="[33]"/>
 *             &lt;enumeration value="[34]"/>
 *             &lt;enumeration value="[35]"/>
 *             &lt;enumeration value="[36]"/>
 *             &lt;enumeration value="[37]"/>
 *             &lt;enumeration value="[38]"/>
 *             &lt;enumeration value="[39]"/>
 *             &lt;enumeration value="[3]"/>
 *             &lt;enumeration value="[40]"/>
 *             &lt;enumeration value="[41]"/>
 *             &lt;enumeration value="[42]"/>
 *             &lt;enumeration value="[43]"/>
 *             &lt;enumeration value="[44]"/>
 *             &lt;enumeration value="[45]"/>
 *             &lt;enumeration value="[48]"/>
 *             &lt;enumeration value="[49]"/>
 *             &lt;enumeration value="[4]"/>
 *             &lt;enumeration value="[51]"/>
 *             &lt;enumeration value="[52]"/>
 *             &lt;enumeration value="[53]"/>
 *             &lt;enumeration value="[55]"/>
 *             &lt;enumeration value="[56]"/>
 *             &lt;enumeration value="[57]"/>
 *             &lt;enumeration value="[58]"/>
 *             &lt;enumeration value="[59]"/>
 *             &lt;enumeration value="[60]"/>
 *             &lt;enumeration value="[62]"/>
 *             &lt;enumeration value="[63]"/>
 *             &lt;enumeration value="[64]"/>
 *             &lt;enumeration value="[67]"/>
 *             &lt;enumeration value="[68]"/>
 *             &lt;enumeration value="[69]"/>
 *             &lt;enumeration value="[70]"/>
 *             &lt;enumeration value="[71]"/>
 *             &lt;enumeration value="[72]"/>
 *             &lt;enumeration value="[73]"/>
 *             &lt;enumeration value="[74]"/>
 *             &lt;enumeration value="[75]"/>
 *             &lt;enumeration value="[76]"/>
 *             &lt;enumeration value="[77]"/>
 *             &lt;enumeration value="[78]"/>
 *             &lt;enumeration value="[79]"/>
 *             &lt;enumeration value="[80]"/>
 *             &lt;enumeration value="[81]"/>
 *             &lt;enumeration value="[82]"/>
 *             &lt;enumeration value="[84]"/>
 *             &lt;enumeration value="[86]"/>
 *             &lt;enumeration value="[87]"/>
 *             &lt;enumeration value="[88]"/>
 *             &lt;enumeration value="[8]"/>
 *             &lt;enumeration value="[90]"/>
 *             &lt;enumeration value="[91]"/>
 *             &lt;enumeration value="[92]"/>
 *             &lt;enumeration value="[93]"/>
 *             &lt;enumeration value="[95]"/>
 *             &lt;enumeration value="[96]"/>
 *             &lt;enumeration value="[97]"/>
 *             &lt;enumeration value="[98]"/>
 *             &lt;enumeration value="[99]"/>
 *             &lt;enumeration value="[9]"/>
 *             &lt;enumeration value="[P0]"/>
 *             &lt;enumeration value="[P1]"/>
 *             &lt;enumeration value="c7"/>
 *             &lt;enumeration value="l asis"/>
 *             &lt;enumeration value="l bar 1"/>
 *             &lt;enumeration value="l bar 2"/>
 *             &lt;enumeration value="l knee 1"/>
 *             &lt;enumeration value="l knee 2"/>
 *             &lt;enumeration value="l mall"/>
 *             &lt;enumeration value="l met"/>
 *             &lt;enumeration value="l should"/>
 *             &lt;enumeration value="l thigh"/>
 *             &lt;enumeration value="r asis"/>
 *             &lt;enumeration value="r bar 1"/>
 *             &lt;enumeration value="r bar 2"/>
 *             &lt;enumeration value="r knee 1"/>
 *             &lt;enumeration value="r knee 2"/>
 *             &lt;enumeration value="r mall"/>
 *             &lt;enumeration value="r met"/>
 *             &lt;enumeration value="r should"/>
 *             &lt;enumeration value="r thigh"/>
 *             &lt;enumeration value="sacrum"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="description" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="data" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="coords" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="X Y Z"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "track")
public class Track {

    @XmlAttribute(name = "scaleFactor", required = true)
    protected short scaleFactor;
    @XmlAttribute(name = "nSegs", required = true)
    protected byte nSegs;
    @XmlAttribute(name = "nPoints", required = true)
    protected short nPoints;
    @XmlAttribute(name = "nItems", required = true)
    protected byte nItems;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "data", required = true)
    protected String data;
    @XmlAttribute(name = "coords", required = true)
    protected String coords;

    /**
     * Gets the value of the scaleFactor property.
     * 
     */
    public short getScaleFactor() {
        return scaleFactor;
    }

    /**
     * Sets the value of the scaleFactor property.
     * 
     */
    public void setScaleFactor(short value) {
        this.scaleFactor = value;
    }

    /**
     * Gets the value of the nSegs property.
     * 
     */
    public byte getNSegs() {
        return nSegs;
    }

    /**
     * Sets the value of the nSegs property.
     * 
     */
    public void setNSegs(byte value) {
        this.nSegs = value;
    }

    /**
     * Gets the value of the nPoints property.
     * 
     */
    public short getNPoints() {
        return nPoints;
    }

    /**
     * Sets the value of the nPoints property.
     * 
     */
    public void setNPoints(short value) {
        this.nPoints = value;
    }

    /**
     * Gets the value of the nItems property.
     * 
     */
    public byte getNItems() {
        return nItems;
    }

    /**
     * Sets the value of the nItems property.
     * 
     */
    public void setNItems(byte value) {
        this.nItems = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the coords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoords() {
        return coords;
    }

    /**
     * Sets the value of the coords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoords(String value) {
        this.coords = value;
    }

}
